<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-24</name>
   <tag></tag>
   <elementGuidId>6bd6ff9c-1635-404b-af22-f0e7f2817abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>277018ac-8d62-4a11-ad2e-c8f347c02804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-24</value>
      <webElementGuid>97581b2c-71a2-4621-958a-6a2b43891b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f3e3e30-5720-451a-9b91-ed7aba6d0818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-24&quot;)</value>
      <webElementGuid>a76809b6-eb4e-4116-abe7-5faa9890c8c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-24']</value>
      <webElementGuid>7090c82b-3e3d-4599-bceb-4261962ccd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[3]/div/div/div/input</value>
      <webElementGuid>e1667753-fce9-43c9-b67b-5a01674df3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>58e9983c-d2b7-4a06-b7ef-3d7d6f8d656e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-24' and @type = 'text']</value>
      <webElementGuid>06ef1013-7384-4cb1-99ca-518c4167236e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
